"""generation_jobs token usage

Revision ID: 322821c28d7d
Revises: 12cc9ccd1d8b
Create Date: 2026-09-09 14:38:21.486565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322821c28d7d'
down_revision: Union[str, None] = '12cc9ccd1d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('generation_jobs', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('generation_jobs', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'total_tokens')
    op.drop_column('generation_jobs', 'output_tokens')
    op.drop_column('generation_jobs', 'input_tokens')
    # ### end Alembic commands ###
