"""telegram: channel config, video url, post_target delivery fields

Revision ID: 677d0b17e985
Revises: d6229c4b64fb
Create Date: 2026-09-04 14:30:04.316358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677d0b17e985'
down_revision: Union[str, None] = 'd6229c4b64fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('post_targets', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('post_targets', sa.Column('external_id', sa.String(length=120), server_default='', nullable=False))
    op.add_column('post_targets', sa.Column('error', sa.Text(), server_default='', nullable=False))
    op.add_column('videos', sa.Column('url', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'url')
    op.drop_column('post_targets', 'error')
    op.drop_column('post_targets', 'external_id')
    op.drop_column('post_targets', 'published_at')
    op.drop_column('channels', 'config')
    # ### end Alembic commands ###
