"""auth: password_hash + is_active on team_members

Revision ID: 76d195c5525f
Revises: 677d0b17e985
Create Date: 2026-09-04 14:52:27.921831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d195c5525f'
down_revision: Union[str, None] = '677d0b17e985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False))
    op.add_column('team_members', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_column('team_members', 'is_active')
    op.drop_column('team_members', 'password_hash')
    # ### end Alembic commands ###
